### PR TITLE
pass headers to handlers

### PR DESCRIPTION
**Pull request by alikhani**
I need to check the headers in the handler

### CODE REVIEW

**Comment by possibilities** [comment]
Ah, I recently added `req` and `res` for the same reason and then forgot to push up the new version. Work for you?

**Comment by possibilities** [comment]
I really need to write some basic documentation but here's the test https://github.com/possibilities/micro-api/blob/master/test.js#L49

**Comment by possibilities** [comment]
Actually maybe it's wiser to pass in headers like you suggest. Probably best to pass in the pieces we need and avoid causing temptation to touch req/res?

**Comment by possibilities** [comment]
Feel free to bring your PR up (update tests and remove req/res) or I'm happy to do it later tonight.

**Comment by alikhani** [comment]
Maybe req/res would be better though.. res could be nice if one would want custom error-handling and set status codes or headers..? It's more customizable.

**Comment by possibilities** [comment]
Agreed! (;

**Pull request merged**
