### PR TITLE
Sending custom error status code.

### PR DESCRIPTION
**Pull request by saggiyogesh**
Fix for custom error status code. Currently it's ignoring & sending 500.

### CODE REVIEW

**Review by possibilities — COMMENTED** [review]
Cool, mind adding a test?

**Comment by saggiyogesh** [comment]
Done. Added test.

**Comment by saggiyogesh** [comment]
Any updates on merge please.

**Comment by possibilities** [comment]
Oh sorry, I was investigating why the tests didn't run on circleci and got distracted away from this...
I toggled the switch that will incite forks to run the tests also... would you mind triggering it on your branch somehow? Worst case you can do a `git commit --amend -C HEAD && git push force` to force a new sha1.

**Comment by possibilities** [comment]
I squashed and pushed up your branch and made a new PR from it at #10. Will merge that in a moment. Thanks!

**Pull request closed without merging**
